# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/configurator.ui'
#
# Created: Tue Oct 30 04:05:24 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(670, 512)
        Dialog.setWindowTitle(_("AwesomeTTS :: Configuration"))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_logo = QtGui.QLabel(self.frame)
        self.label_logo.setGeometry(QtCore.QRect(100, 10, 240, 46))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo.sizePolicy().hasHeightForWidth())
        self.label_logo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(30)
        self.label_logo.setFont(font)
        self.label_logo.setText(_("AwesomeTTS"))
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.label_version = QtGui.QLabel(self.frame)
        self.label_version.setGeometry(QtCore.QRect(350, 40, 241, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_version.sizePolicy().hasHeightForWidth())
        self.label_version.setSizePolicy(sizePolicy)
        self.label_version.setText(_("Version"))
        self.label_version.setObjectName(_fromUtf8("label_version"))
        self.horizontalLayout_2.addWidget(self.frame)
        spacerItem = QtGui.QSpacerItem(20, 65, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 5, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabfly = QtGui.QWidget()
        self.tabfly.setObjectName(_fromUtf8("tabfly"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabfly)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.tabfly)
        self.label.setText(_("Options of how AwesomeTTS will play the [TTS::] tags on the fly."))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.groupBox = QtGui.QGroupBox(self.tabfly)
        self.groupBox.setTitle(_("Automatic [TTS::] tag Recitation"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cAutoQ = QtGui.QCheckBox(self.groupBox)
        self.cAutoQ.setText(_("Automatically recite [TTS::] tags on Questions"))
        self.cAutoQ.setObjectName(_fromUtf8("cAutoQ"))
        self.verticalLayout_5.addWidget(self.cAutoQ)
        self.cAutoA = QtGui.QCheckBox(self.groupBox)
        self.cAutoA.setText(_("Automatically recite [TTS::] tags on Answers"))
        self.cAutoA.setObjectName(_fromUtf8("cAutoA"))
        self.verticalLayout_5.addWidget(self.cAutoA)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tabfly)
        self.groupBox_2.setTitle(_("Keyboard Shortcuts"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setText(_("Key to read [TTS::] tags on Questions"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.pushKeyQ = QtGui.QPushButton(self.groupBox_2)
        self.pushKeyQ.setText(_("PushButton"))
        self.pushKeyQ.setObjectName(_fromUtf8("pushKeyQ"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.pushKeyQ)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setText(_("Key to read [TTS::] tags on Answer"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.pushKeyA = QtGui.QPushButton(self.groupBox_2)
        self.pushKeyA.setText(_("PushButton"))
        self.pushKeyA.setObjectName(_fromUtf8("pushKeyA"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.pushKeyA)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tabfly)
        self.groupBox_3.setTitle(_("Subprocessing"))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cSubprocessing = QtGui.QCheckBox(self.groupBox_3)
        self.cSubprocessing.setText(_("Enable Subprocessing"))
        self.cSubprocessing.setObjectName(_fromUtf8("cSubprocessing"))
        self.verticalLayout.addWidget(self.cSubprocessing)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setText(_("There is a bug of cutting the ending of a speech when enabled on Windows XP or Mac OS X.\n"
"If it\'s disabled, Anki will be frozen while AwesomeTTS recites the speech.\n"
"If you are having problems, stick with the MP3 Generator."))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tabfly, _fromUtf8(""))
        self.tabmp3 = QtGui.QWidget()
        self.tabmp3.setObjectName(_fromUtf8("tabmp3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabmp3)
        self.groupBox_4.setGeometry(QtCore.QRect(9, 40, 631, 91))
        self.groupBox_4.setTitle(_("Filename"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setText(_("How should AwesomeTTS name the files it generate?"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.rfilename_plain = QtGui.QRadioButton(self.groupBox_4)
        self.rfilename_plain.setToolTip(_("<html><head/><body><p>Unix users can choose this option without problem.<br/>It will work alright sync with AnkiMobile, but it won\'t work with AnkiWeb<br/><br/>Examples:<br/>sp&#233;cial.mp3<br/>&#12399;&#12356;.mp3<br/>&#20320;&#22909;.mp3</p></body></html>"))
        self.rfilename_plain.setText(_("Use the input text without quotation for special characters (it doesn\'t work well on Windows)"))
        self.rfilename_plain.setObjectName(_fromUtf8("rfilename_plain"))
        self.verticalLayout_3.addWidget(self.rfilename_plain)
        self.rfilename_quoted = QtGui.QRadioButton(self.groupBox_4)
        self.rfilename_quoted.setToolTip(_("<html><head/><body><p>Examples:<br/>spC3A9cial.mp3<br/>E381AFE38184.mp3<br/>E4BDA0E5A5BD.mp3</p></body></html>"))
        self.rfilename_quoted.setText(_("Use the input text with quotation for special characters"))
        self.rfilename_quoted.setObjectName(_fromUtf8("rfilename_quoted"))
        self.verticalLayout_3.addWidget(self.rfilename_quoted)
        self.label_6 = QtGui.QLabel(self.tabmp3)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 481, 16))
        self.label_6.setText(_("Options of how AwesomeTTS will generate MP3 files."))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.tabWidget.addTab(self.tabmp3, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabfly), _("On the Fly"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabmp3), _("MP3 Generator"))

