# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/massgenerator.ui'
#
# Created: Tue Oct 16 05:22:27 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(670, 410)
        Dialog.setWindowTitle(_("AwesomeTTS :: MP3 Mass Generator"))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setText(_("Service:"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.comboBoxService = QtGui.QComboBox(Dialog)
        self.comboBoxService.setObjectName(_fromUtf8("comboBoxService"))
        self.verticalLayout_2.addWidget(self.comboBoxService)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.verticalLayout_2.addWidget(self.stackedWidget)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setText(_("AwesomeTTS will generate MP3 files to all selected nodes."))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.sourceFieldComboBox = QtGui.QComboBox(Dialog)
        self.sourceFieldComboBox.setObjectName(_fromUtf8("sourceFieldComboBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sourceFieldComboBox)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setText(_("Destination Field"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.destinationFieldComboBox = QtGui.QComboBox(Dialog)
        self.destinationFieldComboBox.setObjectName(_fromUtf8("destinationFieldComboBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.destinationFieldComboBox)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setText(_("Source Field"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.radioEndof = QtGui.QRadioButton(Dialog)
        self.radioEndof.setText(_("Write the [sound:] tag at the end of the Destination Field."))
        self.radioEndof.setChecked(True)
        self.radioEndof.setObjectName(_fromUtf8("radioEndof"))
        self.verticalLayout.addWidget(self.radioEndof)
        self.radioOverwrite = QtGui.QRadioButton(Dialog)
        self.radioOverwrite.setText(_("Overwrite the Destination Field with the sound file path."))
        self.radioOverwrite.setObjectName(_fromUtf8("radioOverwrite"))
        self.verticalLayout.addWidget(self.radioOverwrite)
        self.checkBoxSndTag = QtGui.QCheckBox(Dialog)
        self.checkBoxSndTag.setEnabled(True)
        self.checkBoxSndTag.setText(_("Generate the sound file path within the [sound:] tag."))
        self.checkBoxSndTag.setChecked(True)
        self.checkBoxSndTag.setObjectName(_fromUtf8("checkBoxSndTag"))
        self.verticalLayout.addWidget(self.checkBoxSndTag)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 5, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_logo = QtGui.QLabel(self.frame)
        self.label_logo.setGeometry(QtCore.QRect(100, 10, 240, 46))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo.sizePolicy().hasHeightForWidth())
        self.label_logo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(30)
        self.label_logo.setFont(font)
        self.label_logo.setText(_("AwesomeTTS"))
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.label_version = QtGui.QLabel(self.frame)
        self.label_version.setGeometry(QtCore.QRect(350, 40, 241, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_version.sizePolicy().hasHeightForWidth())
        self.label_version.setSizePolicy(sizePolicy)
        self.label_version.setText(_("Version"))
        self.label_version.setObjectName(_fromUtf8("label_version"))
        self.horizontalLayout_2.addWidget(self.frame)
        spacerItem1 = QtGui.QSpacerItem(20, 65, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        pass

